# Copyright (c) 2025-2026 Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause

import os

import platformdirs

__version__ = "2.0.0"

# Configs bundled with the package. Only the synthesized FTDI Alpaca-Lite
# default (TAC_FTDI_13.pinout.json) ships here; the full config set (a
# .pinout.json per board plus devicelist.json) is fetched and converted with
# the "installconfigs" subcommand.
PACKAGE_TAC_CONFIG_PATH = os.path.join(os.path.dirname(__file__), "tac_configs")

# Where "installconfigs" writes the full config set by default.
INSTALLED_TAC_CONFIG_PATH = platformdirs.user_data_dir("pytactl")

# Default config repository fetched by "installconfigs".
DEFAULT_CONFIG_REPOSITORY = (
    "https://github.com/qualcomm/qcom-test-automation-controller/"
)

# Filename of the default FTDI Alpaca-Lite config used as a fallback. The upstream
# repository has no config file for it (it is generated by
# FTDIPlatformConfiguration.cpp), so "installconfigs" copies the bundled pinout
# below under this name.
DEFAULT_CONFIG_FILENAME = "default.pinout.json"

# The same config under the name it has in the config set shipped with the
# package, where there is no need for a copy under the generic name.
BUNDLED_DEFAULT_CONFIG_FILENAME = "TAC_FTDI_13.pinout.json"


def default_tac_config_path():
    """Resolve the default TAC config directory.

    Prefer the installed config set (populated by "installconfigs") when it
    exists and is non-empty; otherwise fall back to the configs bundled with
    the package.
    """
    installed = INSTALLED_TAC_CONFIG_PATH
    if os.path.isdir(installed) and os.listdir(installed):
        return installed
    return PACKAGE_TAC_CONFIG_PATH


def default_config_file(tac_config_path):
    """Path of the fallback FTDI Alpaca-Lite config inside a config directory.

    It goes under two names, both legitimate: a directory populated by
    "installconfigs" holds a copy named DEFAULT_CONFIG_FILENAME, while the set
    shipped with the package keeps the config under its own name. Returns
    ``None`` when the directory holds neither.
    """
    for name in (DEFAULT_CONFIG_FILENAME, BUNDLED_DEFAULT_CONFIG_FILENAME):
        candidate = os.path.join(tac_config_path, name)
        if os.path.exists(candidate):
            return candidate
    return None


# Backwards-compatible module-level default; resolved at import time.
DEFAULT_TAC_CONFIG_PATH = default_tac_config_path()
