# Copyright (c) 2026 Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause

"""Compare the vendored TAC configs with upstream and sync what changed.

Converts the configs in a qcom-test-automation-controller checkout to the shared
pinout format (the same conversion "pytactl convertconfigs" runs) and compares
the result, file by file, with the set vendored in pytactl/tac_configs/.

A file that differs is either *known* or *new*. Known differences are upstream
changes deliberately not taken into pytactl; they are listed in
scripts/known-config-differences.json, each with a fingerprint of the upstream
content it was reviewed against. A difference is new when the file is not
listed there, or when upstream has changed it again since, so that its
fingerprint no longer matches.

With --apply, new differences are written into the vendored set (each file
stamped with the upstream commit it now comes from) and known ones are left
alone. Entries in the known-differences file that no longer describe a
difference are dropped. Nothing else is touched, so a run with nothing new
leaves the tree clean - which is what the upstream-config-sync workflow relies
on to decide whether to open a pull request.

With --update-known, every current difference is recorded as known instead:
the way to accept a difference as one to keep out of pytactl.

The provenance annotation ("source") is excluded from the comparison: it names
the upstream commit, which moves with every upstream push, config change or not.
"""

import argparse
import hashlib
import json
import os
import subprocess
import sys
import tempfile

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, REPO_ROOT)

from pytactl import BUNDLED_DEFAULT_CONFIG_FILENAME, tacconfig  # noqa: E402

UPSTREAM_REPOSITORY = "https://github.com/qualcomm/qcom-test-automation-controller.git"
UPSTREAM_CONFIG_PATH = "configurations"
DEVICE_LIST = "devicelist.json"

DEFAULT_CONFIGS = os.path.join(REPO_ROOT, "pytactl", "tac_configs")
DEFAULT_KNOWN = os.path.join(REPO_ROOT, "scripts", "known-config-differences.json")

# Vendored files with no upstream counterpart: the FTDI Alpaca-Lite default is
# generated by QTAC code rather than stored as a config upstream.
LOCAL_ONLY = {BUNDLED_DEFAULT_CONFIG_FILENAME}

# Fingerprint of a file upstream no longer has.
REMOVED = "removed"


def load_json(path):
    with open(path) as handle:
        return json.load(handle)


def write_json(path, obj):
    with open(path, "w") as handle:
        json.dump(obj, handle, indent=4)
        handle.write("\n")


def comparable(config):
    """``config`` without its provenance annotation."""
    return {k: v for k, v in config.items() if k != tacconfig.SOURCE_FIELD}


def fingerprint(config):
    """Stable hash of a converted upstream config, provenance excluded."""
    if config is None:
        return REMOVED
    canonical = json.dumps(comparable(config), sort_keys=True, separators=(",", ":"))
    return "sha256:" + hashlib.sha256(canonical.encode()).hexdigest()


def config_names(directory):
    return {
        name
        for name in os.listdir(directory)
        if name.endswith(tacconfig.PINOUT_EXTENSION) or name == DEVICE_LIST
    }


def upstream_commit(checkout):
    return subprocess.run(
        ["git", "-C", checkout, "rev-parse", "HEAD"],
        capture_output=True,
        text=True,
        check=True,
    ).stdout.strip()


def convert_upstream(checkout, destination, commit, repository):
    source = os.path.join(checkout, UPSTREAM_CONFIG_PATH)
    result = tacconfig.convert_directory(
        source,
        destination,
        default_filename=BUNDLED_DEFAULT_CONFIG_FILENAME,
        source_info={
            "repository": repository,
            "commit": commit,
            "path": UPSTREAM_CONFIG_PATH,
        },
    )
    for name, error in result["failed"]:
        print(f"warning: {name} could not be converted: {error}", file=sys.stderr)
    return result


def compare(configs, converted):
    """Return ``{name: (vendored, upstream)}`` for every file that differs.

    Either side is ``None`` when the file exists only on the other.
    """
    differences = {}
    for name in sorted((config_names(configs) | config_names(converted)) - LOCAL_ONLY):
        vendored_path = os.path.join(configs, name)
        upstream_path = os.path.join(converted, name)
        vendored = load_json(vendored_path) if os.path.exists(vendored_path) else None
        upstream = load_json(upstream_path) if os.path.exists(upstream_path) else None
        if (
            vendored is None
            or upstream is None
            or comparable(vendored) != comparable(upstream)
        ):
            differences[name] = (vendored, upstream)
    return differences


def describe(vendored, upstream):
    if vendored is None:
        return "new upstream file"
    if upstream is None:
        return "removed upstream"
    fields = sorted(
        key
        for key in set(comparable(vendored)) | set(comparable(upstream))
        if vendored.get(key) != upstream.get(key)
    )
    return "changed: " + ", ".join(f"`{field}`" for field in fields)


def dangling_catalog_entries(configs):
    """configPath values in the vendored devicelist.json with no config file."""
    path = os.path.join(configs, DEVICE_LIST)
    if not os.path.exists(path):
        return []
    return sorted(
        {
            entry.get("configPath")
            for entry in load_json(path).get("catalog", [])
            if not os.path.exists(os.path.join(configs, entry.get("configPath", "")))
        }
    )


def write_summary(path, commit, repository, new, known, stale, dangling, known_path):
    web = repository.removesuffix(".git")
    lines = [
        "Sync of the vendored TAC configs in `pytactl/tac_configs/` with "
        f"[qcom-test-automation-controller]({web}) at "
        f"[`{commit[:12]}`]({web}/commit/{commit}).",
        "",
        "## New upstream differences (applied)",
        "",
    ]
    for name, (detail, was_known) in new.items():
        suffix = (
            " - **was a known difference**, but upstream has changed it again; "
            "the upstream file is taken in full"
            if was_known
            else ""
        )
        lines.append(f"- `{name}`: {detail}{suffix}")
    if not new:
        lines.append("- none")

    lines += ["", "## Known differences (not applied)", ""]
    lines += [f"- `{name}`: {detail}" for name, detail in known.items()] or ["- none"]

    if stale:
        lines += [
            "",
            "## Known-difference entries dropped",
            "",
            "These no longer differ from upstream:",
            "",
        ]
        lines += [f"- `{name}`" for name in stale]

    if dangling:
        lines += [
            "",
            "## Warning: devicelist.json points at configs not vendored",
            "",
        ]
        lines += [f"- `{name}`" for name in dangling]
        lines += [
            "",
            "The catalog was updated but these configs are held back as known "
            "differences; the bundled-config tests will fail until that is "
            "resolved.",
        ]

    relative_known = os.path.relpath(known_path, REPO_ROOT)
    lines += [
        "",
        "To keep a difference out of pytactl instead, revert that file in this "
        f"branch and run `python scripts/sync_upstream_configs.py <checkout> "
        f"--update-known` to record it in `{relative_known}`.",
    ]
    with open(path, "w") as handle:
        handle.write("\n".join(lines) + "\n")


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("checkout", help="qcom-test-automation-controller git checkout")
    parser.add_argument(
        "--configs", default=DEFAULT_CONFIGS, help="vendored config directory"
    )
    parser.add_argument("--known", default=DEFAULT_KNOWN, help="known-differences file")
    parser.add_argument(
        "--repository",
        default=UPSTREAM_REPOSITORY,
        help="repository URL recorded in the configs' provenance",
    )
    action = parser.add_mutually_exclusive_group()
    action.add_argument(
        "--apply",
        action="store_true",
        help="write new differences into the vendored set",
    )
    action.add_argument(
        "--update-known",
        action="store_true",
        help="record every current difference as known",
    )
    parser.add_argument("--summary", help="write a Markdown summary to this file")
    args = parser.parse_args()

    commit = upstream_commit(args.checkout)
    known_file = (
        load_json(args.known) if os.path.exists(args.known) else {"differences": {}}
    )
    known_entries = known_file.setdefault("differences", {})

    with tempfile.TemporaryDirectory(prefix="pytactl-upstream-") as converted:
        convert_upstream(args.checkout, converted, commit, args.repository)
        differences = compare(args.configs, converted)

        new = {}
        known = {}
        for name, (vendored, upstream) in differences.items():
            detail = describe(vendored, upstream)
            entry = known_entries.get(name)
            if entry and entry.get("fingerprint") == fingerprint(upstream):
                known[name] = detail
            else:
                new[name] = (detail, entry is not None)
        stale = sorted(set(known_entries) - set(differences))

        print(f"Upstream {args.repository} at {commit}")
        for name, detail in known.items():
            print(f"known  {name}: {detail}")
        for name, (detail, was_known) in new.items():
            note = " (known difference changed upstream)" if was_known else ""
            print(f"NEW    {name}: {detail}{note}")
        for name in stale:
            print(f"stale  {name}: listed as known but no longer differs")

        if args.update_known:
            known_file["differences"] = {
                name: {
                    **known_entries.get(name, {}),
                    "fingerprint": fingerprint(upstream),
                    "upstream_commit": commit,
                }
                for name, (_, upstream) in differences.items()
            }
            write_json(args.known, known_file)
            print(f"Recorded {len(differences)} known difference(s) in {args.known}")
            return 0

        if args.apply:
            for name in new:
                upstream_path = os.path.join(converted, name)
                vendored_path = os.path.join(args.configs, name)
                if os.path.exists(upstream_path):
                    write_json(vendored_path, load_json(upstream_path))
                else:
                    os.remove(vendored_path)
                known_entries.pop(name, None)
            for name in stale:
                del known_entries[name]
            if new or stale:
                write_json(args.known, known_file)

    if args.summary:
        dangling = dangling_catalog_entries(args.configs) if args.apply else []
        write_summary(
            args.summary,
            commit,
            args.repository,
            new,
            known,
            stale,
            dangling,
            args.known,
        )

    # Without --apply, a non-zero exit flags that the vendored set is behind.
    if not args.apply and (new or stale):
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
